### ISSUE TITLE
Can Bus data are not shown properly

### ISSUE THREAD

**Issue by konsgken** [foxglove/nuscenes2bag#10]
[](url)**Description**

Hi,

I have tried to run the nuscenes2bag notebook but the can bus data are not shown properly (see image). I have run the setup.sh script (it succeeds without errors) and I have used the Dockerfile that you provided. In this figure, I used the nuScenes mini dataset (scene-0061) and I have tried to plot the angular velocity in x-direction.

**Unexpected Behavior**
![example](https://user-images.githubusercontent.com/44728045/211525215-9cf5a0f0-72a4-418d-aaef-765cfcc4c88f.png)

**Comment by konsgken** [comment]
It seems that the problem was in these lines:

```python 
       for (msg_stamp, topic, msg) in can_msg_events:
            bag.write(topic, msg, stamp)
```

I changed stamp to msg_stamp
```python 
       for (msg_stamp, topic, msg) in can_msg_events:
            bag.write(topic, msg, msg_stamp)
```

**Comment by amacneil** [comment]
You can also click the `...` in Foxglove plot settings next to the series, and change it from `Receive timestamp` to `header.stamp`:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/637671/211657310-2ef97697-4aa7-448c-9a3a-edad094e6df7.png">

This project is no longer maintained, there is an updated conversion script at https://github.com/foxglove/nuscenes2mcap
