### ISSUE TITLE
radar lidar and camera topics not created 

### ISSUE THREAD

**Issue by balajiv18** [foxglove/nuscenes2bag#2]
Hi, Thanks for creating this program. Its really great. I do need a little help. I used the program and converted nuscenes to bag file. When I tried to access this file in foxglove, there are no topics displayed for radar, lidar and cameras. Thanks in advance

**Comment by jhurliman** [comment]
This is likely due to missing downloads from nuscenes.org. Check that the `setup.sh` script succeeds without errors.
